export const experiences = [
  {
    id: "1",
    title: "Kayaking",
    location: "Udupi",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202025-10-28%20194106-tn6guSSX5sUdOIfNcnO4H5Z0wTSIrS.png",
    price: 999,
    description: "Curated small-group experience. Certified guide. Safety first with gear included.",
    about: "Scenic routes, trained guides, and safety briefing. Minimum age 10.",
  },
  {
    id: "2",
    title: "Kayaking",
    location: "Udupi, Karnataka",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202025-10-28%20194023-eVbvlVMArjHNImoI9UpBo2qWS9ljOs.png",
    price: 999,
    description: "Curated small-group experience. Certified guide. Safety first with gear included.",
    about: "Scenic routes, trained guides, and safety briefing. Minimum age 10.",
  },
  {
    id: "3",
    title: "Nandi Hills Sunrise",
    location: "Bangalore",
    image: "/sunrise-over-hills.jpg",
    price: 899,
    description: "Watch the sunrise from the majestic Nandi Hills with a certified guide.",
    about: "Early morning trek with breakfast included. Minimum age 8.",
  },
  {
    id: "4",
    title: "Coffee Trail",
    location: "Coorg",
    image: "/coffee-plantation-trail.jpg",
    price: 1299,
    description: "Explore coffee plantations and learn about coffee cultivation.",
    about: "Guided plantation tour with coffee tasting. Minimum age 5.",
  },
  {
    id: "5",
    title: "Boat Cruise",
    location: "Sunderban",
    image: "/boat-cruise-river.jpg",
    price: 999,
    description: "Scenic boat cruise through mangrove forests and wildlife spotting.",
    about: "Professional guides and safety equipment provided. Minimum age 6.",
  },
  {
    id: "6",
    title: "Bunjee Jumping",
    location: "Marali",
    image: "/bungee-jumping-adventure.jpg",
    price: 999,
    description: "Thrilling bungee jumping experience with certified instructors.",
    about: "All safety gear included. Minimum age 18. Weight limit 140kg.",
  },
  {
    id: "7",
    title: "Nandi Hills Sunrise",
    location: "Bangalore",
    image: "/mountain-sunrise-view.jpg",
    price: 899,
    description: "Experience the breathtaking sunrise from Nandi Hills.",
    about: "Early morning trek with breakfast. Minimum age 8.",
  },
  {
    id: "8",
    title: "Coffee Trail",
    location: "Coorg",
    image: "/coffee-plantation-landscape.jpg",
    price: 1299,
    description: "Immerse yourself in the coffee culture of Coorg.",
    about: "Full day tour with lunch included. Minimum age 5.",
  },
]
